/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.egcc.bookstoreapp.view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import pe.egcc.bookstoreapp.controller.CrudPublicacionController;
import pe.egcc.bookstoreapp.model.Publicacion;
import pe.egcc.bookstoreapp.util.AppUtil;
import pe.egcc.bookstoreapp.util.Mensaje;
import pe.egcc.bookstoreapp.util.Session;

/**
 *
 * @author Gabo
 */
public class CrudPublicacionView extends javax.swing.JInternalFrame {

  private List<Publicacion> lista = new ArrayList<>();

  public CrudPublicacionView() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    btnNuevo = new javax.swing.JButton();
    btnEditar = new javax.swing.JButton();
    btnEliminar = new javax.swing.JButton();
    btnCerrar = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    tblData = new javax.swing.JTable();
    jLabel1 = new javax.swing.JLabel();
    txtIDpublicacion = new javax.swing.JTextField();
    btnBuscar = new javax.swing.JButton();

    btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/egcc/bookstoreapp/img/24x24/nuevo.png"))); // NOI18N
    btnNuevo.setToolTipText("Nuevo");
    btnNuevo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnNuevoActionPerformed(evt);
      }
    });

    btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/egcc/bookstoreapp/img/24x24/editar.png"))); // NOI18N
    btnEditar.setToolTipText("Editar");
    btnEditar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnEditarActionPerformed(evt);
      }
    });

    btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/egcc/bookstoreapp/img/24x24/eliminar.png"))); // NOI18N
    btnEliminar.setToolTipText("Eliminar");
    btnEliminar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnEliminarActionPerformed(evt);
      }
    });

    btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/egcc/bookstoreapp/img/24x24/salir.png"))); // NOI18N
    btnCerrar.setToolTipText("Salir");
    btnCerrar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCerrarActionPerformed(evt);
      }
    });

    tblData.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "ID Publicacion", "Titulo", "Autor", "N° Edicion", "Precio", "Stock"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Integer.class
      };
      boolean[] canEdit = new boolean [] {
        false, false, false, false, false, false
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    jScrollPane1.setViewportView(tblData);

    jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
    jLabel1.setText("ID de Publicacion");

    txtIDpublicacion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

    btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/egcc/bookstoreapp/img/24x24/buscar.png"))); // NOI18N
    btnBuscar.setToolTipText("Buscar");
    btnBuscar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnBuscarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1)
          .addGroup(layout.createSequentialGroup()
            .addGap(27, 27, 27)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(txtIDpublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(84, 84, 84)
            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(39, 39, 39)
            .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(47, 47, 47)
            .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(33, 33, 33)
            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(67, 67, 67)
            .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 186, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
          .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtIDpublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(btnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

      CrudPublicacionEditView view;
      view = new CrudPublicacionEditView(null, true);
      view.setAccion(AppUtil.CRUD_NUEVO);

      Session.put("bean", null);
      view.setVisible(true);

      if (Session.get("bean") != null) {
        Publicacion bean = (Publicacion) Session.get("bean");
        lista.add(bean);
        cargarDatos();
      }

    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

      int row = tblData.getSelectedRow();

      if (row == -1) {
        return;
      }

      CrudPublicacionEditView view;
      view = new CrudPublicacionEditView(null, true);
      view.setAccion(AppUtil.CRUD_EDITAR);
      view.setRowData(lista.get(row));

      Session.put("bean", null);
      view.setVisible(true);

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

      int row = tblData.getSelectedRow();

      if (row == -1) {
        return;
      }

      CrudPublicacionEditView view;
      view = new CrudPublicacionEditView(null, true);
      view.setAccion(AppUtil.CRUD_ELIMINAR);
      view.setRowData(lista.get(row));
      Session.put("bean", null);
      view.setVisible(true);

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
      this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
      try {

        // Datos
        String idpublicacion = txtIDpublicacion.getText();

        // Proceso
        CrudPublicacionController control = new CrudPublicacionController();
        lista = control.read(idpublicacion);

        // Mostrar datos
        cargarDatos();

      } catch (Exception e) {
        Mensaje.showError(rootPane, e.getMessage());
      }
    }//GEN-LAST:event_btnBuscarActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnBuscar;
  private javax.swing.JButton btnCerrar;
  private javax.swing.JButton btnEditar;
  private javax.swing.JButton btnEliminar;
  private javax.swing.JButton btnNuevo;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable tblData;
  private javax.swing.JTextField txtIDpublicacion;
  // End of variables declaration//GEN-END:variables

  private void cargarDatos() {

    // Acceso al objeto Table
    DefaultTableModel tabla;
    tabla = (DefaultTableModel) tblData.getModel();

    // Eliminar  todas las filas
    tabla.setRowCount(0);

    // Cargar Datos
    for (Publicacion pub : lista) {
      Object[] rowData = {
        pub.getIdpublicacion(),
        pub.getTitulo(),
        pub.getAutor(),
        pub.getNroedicion(),
        pub.getPrecio(),
        pub.getStock()
      };
      tabla.addRow(rowData);
    }

  }

}
